Clarify TimeRange validity periods
sigstore/protobuf-specs pull request #78
Opened 2023-04-24 19:16 UTC by znewman01

2023-04-24 19:30 UTC, loosebazooka approved these changes
nice, thanks!

2023-04-24 19:40 UTC, haydentherapper approved these changes

2023-04-25 05:54 UTC, kommendorkapten requested changes
This comments are now in conflict with the definition of a `TimeRange`:

https://github.com/sigstore/protobuf-specs/blob/main/protos/sigstore_common.proto#L190

> // The time range is half-open and does not include the end timestamp,
> // i.e [start, end).

We should pick one definition and be consistent IMO.

I would be in favour of using the already defined (Half open), but are open for discussion.

edit: fixed a broken sentence.

2023-04-25 07:20 UTC, kommendorkapten commented
sigstore-js is *inclusive* for both certificate and transparency log verification:
https://github.com/sigstore/sigstore-js/blob/b4e96a2df70abbcb0cc210f50568de04d46c23e8/src/ca/verify/chain.ts#L74
https://github.com/sigstore/sigstore-js/blob/b4e96a2df70abbcb0cc210f50568de04d46c23e8/src/tlog/verify/set.ts#L114

So this may indicate that we should align with RFC 5280.

@woodruffw any details on how Python client?

2023-04-25 23:14 UTC, znewman01 commented
Good catch. My vote is to align with RFC 5280. I've updated the `TimeRange` comment.

Fortunately, it doesn't *actually* matter—a nanosecond should never make the difference in normal use.

2023-04-25 23:16 UTC, haydentherapper approved these changes

2023-04-25 23:21 UTC, woodruffw commented on protos/sigstore_trustroot.proto
> +	// the `valid_for` time range *and* the entire certificate chain.
Weird spacing/indentation here? 🙂

2023-04-25 23:21 UTC, woodruffw commented
> @woodruffw any details on how Python client?

Looks like we actually have a small bug with this: we're inclusive on `notAfter` but not on `notBefore`. I'll fix that now.

2023-04-25 23:22 UTC, woodruffw commented
> Good catch. My vote is to align with RFC 5280. I've updated the `TimeRange` comment.

Strong agree!

2023-04-25 23:23 UTC, znewman01 commented on protos/sigstore_trustroot.proto
> +	// the `valid_for` time range *and* the entire certificate chain.
whoops, was tabs

2023-04-25 23:23 UTC, haydentherapper approved these changes

2023-04-26 05:43 UTC, kommendorkapten approved these changes
Nice!

2023-04-26 05:43 UTC, merged